account_id = "d0c5d93007bf8434609ea82cb7251a61"
name = "blahmx"
type = "webpack"
workers_dev = true
route="blah.mx/*"
zone_id="e30209b1be8a09171193b652c87fcf53"
site = {bucket = "./public",entry-point = "workers-site"}
compatibility_date = "2021-09-16"