account_id = "d0c5d93007bf8434609ea82cb7251a61"
name = "blahmx"
workers_dev = true
bucket = "./public"
route="blah.mx/*"
main = "workers-site/index.js"
site = {bucket = "./public"}
compatibility_date = "2021-09-16"